### ISSUE TITLE
Windows DLL Dependency mismatch causes runtime DLL load failures.

### ISSUE THREAD

**Issue by MSeal** [conda-forge/pywin32-feedstock#18] opened 2019-10-08 21:21 UTC
Issue: Windows DLL Dependency mismatch causes runtime DLL load failures.

I believe the issue arises around how https://github.com/conda-forge/pywin32-feedstock/blob/master/recipe/meta.yaml#L17 is pulling DLLs for new versions of pywin32. The thread in the Environments section describes the issue more thoroughly. I'm echoing the issue here for visibility where the root problem is likely located.

<br/>

Environment (<code>conda list</code>):

<br/>
See https://github.com/mhammond/pywin32/issues/1409 for environment context information

**Comment by carlodri** [comment] 2019-11-19 07:35
Hi @MSeal sorry for the late reply. I think I understand the problem here, I'm going to attempt a fix in #20, I would appreciate your help there particularly in the implementation of a test to catch this issue in the CI.

**Comment by MSeal** [comment] 2019-11-19 19:40
@carlodri I was mostly trying to be a helpful citizen and create an issue in the correct place for the linked report in pywin32. I'm unlikely to able to help in any real capacity on this issue for a while given the other threads in other projects I'm already involved in.

**Comment by nicoddemus** [comment] 2019-11-19 21:54
Sure @MSeal, we appreciate the report nonethless!

**Comment by carlodri** [comment] 2020-02-20 21:13
Hi @MSeal sorry it took very long for me to look into the issue, but I am quite busy with other work matters.

I must definitely be missing something from your comment https://github.com/mhammond/pywin32/issues/1409#issuecomment-538679568 but I cannot reproduce the issue on my Win10 system, _i.e._ inside the conda environment the paths seem to point to the correct dll. Could it be that the issue arises because you are mixing pip/venv and conda? If I conda-install pywin32 inside a conda environment I have no issues.

**Comment by MSeal** [comment] 2020-02-20 22:47
Based on https://github.com/mhammond/pywin32/issues/1409 it seems like a caching issue with pywintypes37.dll, so perhaps you have a fresh build with the right dll, but historically it's pulling an outdated dll? I haven't really dug into it but it seems like that type of failure mode.

**Comment by carlodri** [comment] 2020-02-24 20:30
@MSeal I have attempted a fix in the v227 release borrowing some stuff from the Anaconda defaults (#21), let me know if it works...

**Comment by MSeal** [comment] 2020-02-24 20:41
I was mostly just re-reporting the issue from the other thread because downstream users of my projects were mentioning issues on conda. I actually don't have a reproduction or test to confirm this is fixed on my end. It might make sense to ping one of the pywin32 maintainers to take a look instead.

**Comment by carlodri** [comment] 2020-02-24 20:43
ok thanks @MSeal for reporting back!

**Comment by MSeal** [comment] 2020-10-08 18:42
FYI @carlodri getting more reports of the issue persisting in the https://github.com/jupyter/jupyter_core/issues/187 thread, if you wouldn't mind checking on to see if there's a resolution or if it's the same root issue.

**Comment by carlodri** [comment] 2020-10-09 08:01
By looking at the thread, the traceback reported by the OP seems to indicate that he/she has some mixture of Anaconda and some leftovers of a previous or a side-by-side Python installation, which is certainly smelly.

**Comment by carlodri** [comment] 2020-11-06 10:05
Closing since likely root cause is multiple Python installations/leftovers, see referencing issue https://github.com/jupyter/jupyter_core/issues/187#event-3959596758

@MSeal feel free to reopen if issue if you deem there's another problem.

**Closed by carlodri** 2020-11-06 10:05 UTC

**Comment by Tobias-Fischer** [comment] 2021-12-04 03:26
Seems like this is happening again: https://github.com/RoboStack/robostack.github.io/issues/8
